version: '3'

networks:
  search-network:
    driver: bridge

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_app
    networks:
      - search-network